### ISSUE TITLE
Adyen Terminal Api using Local communications features

### ISSUE THREAD

**Issue by mithesh109** [Adyen/adyen-dotnet-api-library#153]
Hello,

I'm trying to integrate Adyen to our POS application using Terminal API over local communications.
I'm currently able to do a basic sale request and refund and tipping. I would like to know if manual capture and tokenization of card details could be done using Terminal API over local area network.

**Comment by AlexandrosMor** [comment]
Hello @mithesh109,

The manual capture is a call independent of terminal api please refer to the [link](https://docs.adyen.com/point-of-sale/manual-capture#capture-payment). In order to create a recurring contract please refer to [link](https://docs.adyen.com/point-of-sale/shopper-recognition#step-1-tokenize-details). This can be done over cloud and local communication. See the following node SaleToAcquirerData.

If you have more questions please contact Adyen's tech support,
Kind regards,
Alexandros
