### ISSUE TITLE
.Net Framework support

### ISSUE THREAD

**Issue by dileepcy** [Adyen/adyen-dotnet-api-library#313]
Could you please add support for targeting .Net framework as well.

**Comment by AlexandrosMor** [comment]
Hello @dileepcy, 

The library supports .net standard 2.0 which is supporting both .net core and .net framework. You can check the matrix from [Microsoft docs ](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)
The library currently supports .net framework 4.6.1 and above. 
Could you share which .Net framework are you testing ?

Kind regards,
Alexandros

**Comment by dileepcy** [comment]
Hi Alexandros- what I mean is if you could add the SDK target framework as .Net461 as well it is more useful.

    
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>  

please refer the below URL for more details

https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file

**Comment by AlexandrosMor** [comment]
Hi @dileepcy,  

The solutions that we are offering should benefit all the merchants so we prefer to keep our solutions generic. .net 4.6.1 is specific and will not benefit a merchant who is using .net core for example that's why we did not add it. 
In my test the library works with 4.6.1 out of the box. Is it not the case for you ?

**Comment by AlexandrosMor** [comment]
Hello @dileepcy,

I believe that your question is answered so I will close this issue. Feel free to open another github issue if you want to report a bug or recommend a library feature.

regards,
Alexandros
