### ISSUE TITLE
Why are classes defined muliple times?

### ISSUE THREAD

**Issue by FrankVDL-Trivec** [Adyen/adyen-dotnet-api-library#362]
Looking at the packages, a lot of classed are defined multiple times.

For example,  **Amount** is found in Models/Amount.cs , Models/CheckOut/Amount.cs and Models/Nexo/Amount.cs

Why is this ?
This also causes a lot of reference issues in our code.

Can the duplicates be removed and follow a more DRY approach ?

**Comment by AlexandrosMor** [comment]
Hello @FrankVDL-Trivec,

Thank you for raising this issue. The models are autogenerated using the open api specs and in checkout there is an Amount model similar to nexo which includes the models for POS and Payments has also and amount class which is the classic integration. The amount classes were there since the previous versions. You can fix it by referring to the specific amount for example `Model.Checkout.Amount`
I hope it helps,

kind regards,
Alexandros
Adyen

**Comment by FrankVDL-Trivec** [comment]
Hello,

The amount is unfortunately not the only model that has duplicates.
I can see why that is when they are being generated but maybe that is not a the best thing to do in a package like this.

**Comment by FrankVDL-Trivec** [comment]
Is is possible to the open-api specs so we can generate our own model.
Now we are required to do this based on the documentation, but it seems this is lacking some details

**Comment by AlexandrosMor** [comment]
Hello @FrankVDL-Trivec,

You can get the open api specs to generate the models from [here](https://github.com/Adyen/adyen-openapi/blob/master/json/CheckoutService-v64.json)

kind regards,
Alexandros
Adyen
