### ISSUE TITLE
[PW-5236]Required Shopper Fields for Pay By Link

### ISSUE THREAD

**Issue by glbotu2** [Adyen/adyen-dotnet-api-library#461]
Hi

Would it be possible to implement the `requiredShopperFields` string array in the SDK, to allow us to add shopper name and email. Possibly with some validation to ensure it's a valid combination of fields (although I get that might be tricky).

https://docs.adyen.com/online-payments/pay-by-link/api#shopper-information

Thanks

**Comment by AlexandrosMor** [comment]
Hello @glbotu2, 

Thank you for pointing this issue.  The issue is that the `requiredShopperFields` is missing from [CreatePaymentLinkRequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/Checkout/CreatePaymentLinkRequest.cs), right ?
You could also use the [contribution](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md) guide and open a pull request 

kind regards,
Alexandros
Adyen

**Comment by jillingk** [comment]
Hi @glbotu2,

With the new releases the required shopper fields have been added, just thought I'd let you know!

Best, Jilling
Adyen
