### ISSUE TITLE
Models/ThreeDSecureData missing DsTransID and ThreeDSVersion

### ISSUE THREAD

**Issue by blueohsix** [Adyen/adyen-dotnet-api-library#561]
https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/Adyen/Model/ThreeDSecureData.cs

The above model does not include ThreeDSVersion and DsTransID and it seems like it should. Not passing a ThreeDSVersion causes the transaction (as shown in the Adyen portal) to default to 1.0.2, regardless of whether or not the transaction is 2.1.0 or 2.2.0.

**Comment by blueohsix** [comment]
Thank you, @AlexandrosMor , PR submitted. https://github.com/Adyen/adyen-dotnet-api-library/pull/565

**Comment by jillingk** [comment]
Hi @blueohsix,

Apologies for the super delayed response. We're are in the middle of automating the model generation for this library hence that we completely missed this issue. However I still wanted to notify that since your request we have updated all our models to checkout v69 and a such these fields were added. Still a massive thanks for wanting to contribute and opening the PR, it is definitely appreciated!

Best, Jilling
Adyen
