### ISSUE TITLE
Unable to access pspReference in the response headers

### ISSUE THREAD

**Issue by PedroRainhoOmnibees** [Adyen/adyen-dotnet-api-library#588]
As described in the title, when calling a service it's not possible to access pspReference or the response headers to read pspReference. The Client.HttpClient should have inside "something" that allows to read the response headers or "something" in the service to read the pspReference from the response.

**Comment by jillingk** [comment]
Hi @PedroRainhoOmnibees,

I'm not sure that I understand where your problem lies. Which services are you calling, where you cannot access the pspReference?

Best, Jilling
Adyen

**Comment by PedroRainhoOmnibees** [comment]
This one: https://checkout-test.adyen.com/checkout/v68/sessions.

psp Reference is returned in the response headers and not on the body and it's not exposed by the CreateCheckoutSessionResponse:

ex: Response headers
Transfer-Encoding chunked
Connection close
Set-Cookie JSESSIONID=04DDE6389AFB7A9AC78AB299F4DFB590.test108e; Path=/checkout; Secure; HttpOnly
pspReference AAAAAAAAAAAAAAA
Date Fri, 03 Jun 2022 13:43:04 GMT
Content-Type application/json;charset=UTF-8

**Comment by jillingk** [comment]
Hey @PedroRainhoOmnibees,

Sessions does not return with pspReference in the response body, you're right about that. This happens, because sessions does not immediately instantiate a payment. The correct way to catch the payment details after the payment has been executed is by [webhooks](https://docs.adyen.com/online-payments/web-components#get-payment-outcome). This way you can also receive the proper pspReference for the payments. The pspReference in the header should not really be of use to you. Hope this helps, let me know if I can help with anything else or if you have additional questions about the matter.

Best, Jilling
Adyen

**Comment by PedroRainhoOmnibees** [comment]
I understand but then it's inconsistent because the psp reference appear in the api logs page not the session ID. Imagine that I'm a selling platform that integrates with the adyen and our customers (adyen customers) uses our platform and they need support to diagnose some problems with the session creation. To help me and to help them I will need to ask them to see the adyen logs and in this case what should I tell them? can you please look at ALL the api logs and try find the session Id? and the customer is going to tell me that I'm crazy, but if I tell them can you please look at the api logs and search by the psp reference? then they will have a quick match and they will find the logs and then we can continue with the analysis. During development I was assured by the Adyen in brasil regarding pix that the psp reference was going to be the same throw the entire payment flow, and the entire payment flow stats with the session and ends with the webhook. This week in tests I've discovered that they are not the same. So that is why either adyen change the api log search to enable search by the sessionID or the integration of .net provides a way to get the psp reference and this can be as simple as access to the response headers.
