### ISSUE TITLE
TermUrl missing from CheckoutRedirectAction.Data dictionary

### ISSUE THREAD

**Issue by zachlewittpgg** [Adyen/adyen-dotnet-api-library#637]
**Issue**
We've just upgraded to version 9.0.0 of the .NET library from 8.2.0. It seems that the payload of the redirect response has changed as the `Data` dictionary on the `CheckoutRedirectAction` no longer contains `TermUrl`. The only values in the dictionary are the `PaReq` and `Md`.

I have checked the release notes for the 9.0.0 release and as far as I can see there is no mention of the removal of this property.

If the TermUrl has intentionally been removed then where should we retrieve the value from instead?

**To reproduce the behavior:**

Submit a payment request using the following test card details and inspect the response:

4212 3456 7890 1237
03/30
737

**Screenshots**
![image](https://user-images.githubusercontent.com/98097691/182666018-bc3dd649-3a05-4f2d-920c-baad600bfc06.png)

**Comment by jillingk** [comment]
Hi @zachlewittpgg,

Thanks for reaching out to us with this issue! The library you were using, exploits the Checkout version 68, and with using the newer library you are bumped to Checkout API v69. I think this is causing the troubles and not something inherent in the library, as not much has changed there. I'm going to discuss this with our checkout team and see if/why they have changed this. I'll come back to you on this.

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @zachlewittpgg,

I just got back from our checkout team that they indeed removed the TermUrl from the CheckoutRedirect for the 3ds2 flow in v69. They did this because to improve the overal flow with a different functionality. Instead now you can just post the PaReq and Md to the url, which should redirect you to an Adyen hosted gluepage!

Hope this helps, if there is anything else please do let me know.

Best, Jilling
Adyen

**Comment by zachlewittpgg** [comment]
Hi @jillingk, thanks for looking into that. I will update our logic to no longer process the TermUrl.
