### ISSUE TITLE
Please, take care of required and nullable fields. In .net 6 is required to have string?

### ISSUE THREAD

**Issue by jovan1996** [Adyen/adyen-dotnet-api-library#639]
Example:

Notification object (webHook)

	public AdyenAmount Amount { get; } // not nullable
	public string EventCode { get; } // not nullable
	public string EventDate { get; } // not nullable
	public string MerchantAccountCode { get; } // not nullable
	public string MerchantReference { get; } // not nullable	
	public string PspReference { get; }  // not nullable
	public string Reason { get; } // not nullable, have text or empty string
	public bool Success { get; } // not nullable
	public Dictionary<string, string> AdditionalData { get; }   // not nullable
	
	public string? **OriginalReference** { get; } _// not nullable only if case when EventCode = PAYOUT_THIRDPARTY | REFUNDED_REVERSED | REFUND_WITH_DATA_
		
	public string? **PaymentMethod** { get; } _// not nullable only if case when EventCode = AUTHORISATION

	public IEnumerable<string>? **Operations** { get; } _// not nullable only if case when EventCode = AUTHORISATION_

**Comment by jillingk** [comment]
Hi @jovan1996,

Thanks a lot for reaching out to us with this. As of yet we have indeed not yet implemented the allowed and required fields in our notification models. This is very much on the roadmap though, however taking some time since we are in the middle of an automation process regarding with these libraries. We appreciate the heads up though!

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @jovan1996,

Actually a little update on this. After discussing it, it seems we want to go more towards a model where the API tells us which fields are required instead of doing this on the library level. Since all this logic is already implement on the api level, that makes the most sense for us. Hope this helps!

Best, Jilling
Adyen
