### ISSUE TITLE
Capture delay in session request cannot be set to zero (0)

### ISSUE THREAD

**Issue by sanderlanghorstredhotminute** [Adyen/adyen-dotnet-api-library#655]
**Description of bug**
As we want to support both pre-authorizations and captures, our account is set to capture mode manual capture.
Using SDK 8.2.0 when presenting a pre-authorization, we start a session without captureDelay. When presenting a payment (with capture) we start a session with captureDelay of zero hours (0). As is the advice of Adyen.
However the property CaptureDelay in [CreateCheckoutSessionRequest](https://github.com/Adyen/adyen-dotnet-api-library/blob/8.2.0/Adyen/Model/Checkout/CreateCheckoutSessionRequest.cs#L334) is of type `int` and has a DataMember attribute with EmitDefaultValue = false. This causes the value zero (0) to be ommitted and thus not possible to automatically capture the payment if needed in this situation.

**To Reproduce**
1. Set account to capture mode `manual capture`
2. Start a payment session with capture delay 0
3. Complete a payment session with payment method `card` (or any other that supports pre-authorizations, specifically Apple Pay)
4. The authorization is not automatically captured.

**Expected behavior**
I expect the authorization to be captured automatically as I set the captureDelay to 0.

**Additional context**
Upgrading to version 8.2 (and frontend library 5) from a previous version (SDK 6 and frontend library 3), as this was working as expected, this is now a big problem.

**Comment by jillingk** [comment]
Hi @sanderlanghorstredhotminute,

Thanks for reaching out with this question and apologies for the delayed response. It turned out that the CaptureDelay object should have been nullable in order to properly distinguish between zero and the int default value (which is indeed zero). I have created a quick PR to address this bug. Hopefully this was not too much of a bother to your workflow!

Best, Jilling
Adyen
