### ISSUE TITLE
Due to non-usage of `ConfigureAwait(false)` the library hangs with .Net 48 Web API code 

### ISSUE THREAD

**Issue by bahrianonline** [Adyen/adyen-dotnet-api-library#789]
**Describe the bug**
Due to non-usage of `ConfigureAwait(false)` the library hangs with .Net 48 Web API code. Ref: https://devblogs.microsoft.com/dotnet/configureawait-faq/

**To Reproduce**
As the code is called to /payments api (using PaymentsService. PaymentsAsync), it never returns. 
I have updated the code as follows and it fixed the issue.

`        public async Task<PaymentResponse> PaymentsAsync(PaymentRequest paymentRequest, RequestOptions requestOptions = null)
        {
            string endpoint = _baseUrl + "/payments";
            return await new ServiceResource(this, endpoint).RequestAsync<PaymentResponse>(paymentRequest.ToJson(), requestOptions, new HttpMethod("POST")).ConfigureAwait(continueOnCapturedContext: false);
        }`

**Expected behavior**
It shouldn't hang.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest

**Additional context**
I tried to create the pull request but don't have the access to do so.

**Comment by bahrianonline** [comment]
Any update on this please?

**Comment by jillingk** [comment]
Hi @bahrianonline,

We have thought about this and it we decided that we'd rather actually not set this continueOnCapturedContext flag to false by default in the ConfigureAwaiter. I definitely see the benefit of setting the default to false throughout the library, for improved performance, avoiding deadlocks etc. However since the .NET default is true, and this setting works in almost every case a developer would find himself in (albeit with some drawbacks), we do think this is the best solution. 

I know it might be a bit tedious to set this flag on every async call, but it prevents a lot of confusion I'm afraid. If you have any good arguments why we definitely should set it to false, we're always open te review this again though.

Best, Jilling
Adyen

**Comment by bahrianonline** [comment]
@jillingk : Thanks for the update. But, as I have mentioned under .Net 4X it creates the hang due to that I had to update the library in my project and use it locally with ConfigureAwait(false). 

You can check this link https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html:

It states clearly about the issue I am facing, as we are using ASP.NET app and it hangs without it:

> **You Don’t Need ConfigureAwait(false), But Still Use It in Libraries**
> 
> Since there is no context anymore, there’s no need for ConfigureAwait(false). Any code that knows it’s running under ASP.NET Core does not need to explicitly avoid its context. In fact, the ASP.NET Core team themselves have dropped the use of ConfigureAwait(false).
> 
> However, I still recommend that you use it in your core libraries - anything that may be reused in other applications. If you have code in a library that may also run in a UI app, or legacy ASP.NET app, or anywhere else there may be a context, then you should still use ConfigureAwait(false) in that library.

**Comment by jillingk** [comment]
Hi @bahrianonline,

We actually reconsidered after talking about it for some time and we will add this functionality with the next major release! There was some confusion from my side on the default behaviour with older .Net versions, however since we do support those versions it is a must to add this. Thanks a lot for bringing this to our attention and giving us some food for thought :)

Best, Jilling
Adyen

**Comment by bahrianonline** [comment]
Hi @jillingk,
Thanks :)
Do you have any specifics about when it will be available? I don't want to release our integration with locally build library.

**Comment by jillingk** [comment]
Hey @bahrianonline,

Just in case you missed it, we released last week! Let me know if you run into anything else.

Best, Jilling
Adyen
