### ISSUE TITLE
PaymentRequest.AdditionalData should be Dictionary<string, object>

### ISSUE THREAD

**Issue by pdavis86** [Adyen/adyen-dotnet-api-library#80]
AdyenECommerceLibrary.Model.Checkout.PaymentRequest has a property of AdditionalData with type Dictionary<string, string> 
The documentation https://docs.adyen.com/checkout/3d-secure-2/3ds2-checkout-api-integration/ shows setting a boolean: "allow3DS2" : true
The documentation https://docs.adyen.com/development-resources/test-cards/result-code-testing/ shows setting an int: "RequestedTestAcquirerResponseCode":6

PaymentRequest.AdditionalData should be changed to type Dictionary<string, object>

**Comment by AlexandrosMor** [comment]
Hello @pdavis86 ,

Creating a dictionary with object type instead of string will definitely allow integer and boolean types, though it is not a good design because it will allow other types as well. additionalData does not support all types like any random objects. Changing it to Object type will remove the type safety and widen the scope for allowing object which are not intended to be passed. Integer and Boolean values in your case could be provided by simply converting it to string without causing any problem. So we are closing this issue and keeping it string only.

kind regards,
Alexandros
Adyen
