### ISSUE TITLE
Serialization with System.Text.Json not working in 10.0.0

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-dotnet-api-library#815]
**Describe the bug**
We were happy to see the release of 10.0.0 with the HttpClient backend and Checkout v70, so thanks for making it happen! We're in the process of performing the upgrade now but we've run in to an issue.

With the 9.x version of this library we were able to serialize/deserialize models from this library with System.Text.Json. That no longer seems to be the case with version 10.0.0 unfortunately.

I don't know whether you consider this a bug or not. I've noticed that the models have converters for Newtonsoft.Json so perhaps we should be using those? Still, it's mildly annoying since our code worked fine with version 9.x. Rewriting to Newtonsoft is also something we would like to avoid since we have been trying to move away from that library.

**To Reproduce**
Serialize a payment method with System.Text.Json and deserialize it again.

**Expected behavior**
In 9.x it worked, and the serialized version of one of our payment methods in the test environment was:

```json
      {
        "fundingSource": null,
        "brand": null,
        "brands": null,
        "configuration": {
          "merchantId": "50",
          "gatewayMerchantId": "AtrainAB_APPTEST_TEST"
        },
        "group": null,
        "inputDetails": null,
        "issuers": null,
        "name": "Google Pay",
        "type": "googlepay"
      }
```

**Actual behavior**
In 10.0.0, the deserialization breaks with the error message: 

```
Each parameter in the deserialization constructor on type 'Adyen.Model.Checkout.PaymentMethod' must
bind to an object property or field on deserialization. Each parameter name must match with a property
or field on the object. The match can be case-insensitive.
```

and the serialized version is:

```json
      {
        "fundingSource": null,
        "brand": null,
        "brands": null,
        "_Configuration": {
          "merchantId": "50",
          "gatewayMerchantId": "AtrainAB_APPDEV_TEST"
        },
        "group": null,
        "inputDetails": null,
        "issuers": null,
        "name": "Google Pay",
        "type": "paywithgoogle"
      }
```

If I had to guess I would say that it is the `_Configuration` property that is problematic.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by BrettButcher** [comment]
I am having a similar issue. I have a working solution with 9.21, and am tempted to go back to it till v10 is shaken down properly and docs are up to date. However, I figured I'd persevere and was advised by support to post on here...
I am successfully generating a CreatCheckoutSessionResponse object and return it from my helper libs to the my own api/controller to send on to the client. However, I am getting a server error (500) with the following error message:

_

> System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Nullable`1[Adyen.Model.Checkout.CreateCheckoutSessionResponse+ModeEnum]'.
>    at System.Text.Json.Serialization.Metadata.JsonParameterInfo`1.InitializeDefaultValue(JsonPropertyInfo matchingProperty)
>    at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializeConstructorParameters(JsonParameterInfoValues[] jsonParameters, Boolean sourceGenMode)
>    at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type type, JsonConverter converter, Type runtimeType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo|112_0(Type type, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type type)
>    at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
>    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType)
>    at System.Text.Json.JsonSerializer.SerializeAsync(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
> --- End of stack trace from previous location ---

_
This is the code that calls the lib and returns the object:
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/39193658/98cf3c9e-6788-4752-bc91-6ce2579c1642)

The breakpoint returning the result has the following value for the CreateCheckoutResponseObject:
![image](https://github.com/Adyen/adyen-dotnet-api-library/assets/39193658/3ce0c34f-c7fd-440f-b3d3-1c68315009b3)

I have the NewtonSoft libs installed, but the error seems to be caused by the system libs as the original poster found...

I have found using the system.text libs that the object contstructors have to be complete. So maybe there is an issue there...

Thanks in advance.

**Comment by wboereboom** [comment]
Hey @jonekdahl , @BrettButcher ,

Apologies for not responding sooner.
I am going to investigate this further with the team, and come back to this ticket when we know more.

I can disclose that we have been trying to make a migration to system.text, and to drop NewtonSoft.
It turns out there are some limitations on System.text that make this migration very difficult for us. We might invest more time in the future, but it's on the back burner for now, unfortunately.

Kind Regards,
Wouter
Adyen

**Comment by AlexandrosMor** [comment]
Hello @jonekdahl, 

We would like to test it further so my question is what do you mean with `models have converters for Newtonsoft.Json`.

kind regards,
Alexandros
Adyen

**Comment by jonekdahl** [comment]
Hi @AlexandrosMor. I was referring to the Newtonsoft `JsonConverter` annotations that is being used in various model classes, for example [here in CheckoutPaymentMethod](https://github.com/Adyen/adyen-dotnet-api-library/blob/26037733bb0db96e17c872bde5bc88e0091e228c/Adyen/Model/Checkout/CheckoutPaymentMethod.cs#L34).

As a side note, we worked around this issue by creating a System.Text.Json converter factory that delegates to `Adyen.Util.JsonOperation` for all `Adyen.Model.*` classes. If anybody is interested in this, I can post some more details in this issue.

**Comment by jillingk** [comment]
Hi @jonekdahl,

Right, so you implemented your own serializer instead of the CheckoutPaymentMethodJsonConverter. I imagine this would work just fine for serialization, deserialization I'm not too sure. 

If you could share me what you did I can take a look about possibly extending these models a bit further so we support System.Text. We looked into completely migrating to System.Text in the past, but that didn't really pan out due to various reasons. If we can easily extend the models, however, I would be open to any suggestion to do so!

Best, Jilling
Adyen

**Comment by jonekdahl** [comment]
Hi @jillingk. I've added a slightly modified version of our STJ (System.Text.Json) converter factory below.

```fsharp
module AdyenModelSerialization

open System
open System.Text.Json
open System.Text.Json.Serialization

// System.Text.Json converters for Adyen models.
// The Adyen model classes have custom converters for Newtonsoft.Json.
// The STJ converter in this module delegates to Newtonsoft to perform the (de)serialization.

type AdyenModelConverter<'T>() =
  inherit JsonConverter<'T>()

  override this.Read(reader: Utf8JsonReader byref, typeToConvert, options): 'T =
    use jsonDocument = JsonDocument.ParseValue(&reader)
    let jsonString = jsonDocument.RootElement.GetRawText()
    Adyen.Util.JsonOperation.Deserialize<'T>(jsonString)

  override this.Write(writer, value, options) =
    let jsonString = Adyen.Util.JsonOperation.SerializeRequest(value)
    writer.WriteRawValue(jsonString)


type AdyenModelConverterFactory() =
  inherit JsonConverterFactory()

  override this.CanConvert(typeToConvert: Type) =
    let typeName = typeToConvert.FullName
    let isAdyenModel = typeName.StartsWith "Adyen.Model."
    isAdyenModel

  override this.CreateConverter(typeToConvert: Type, options) =
    let genericType: Type = typedefof<AdyenModelConverter<_>>
    let converterType: Type = genericType.MakeGenericType [| typeToConvert |]
    Activator.CreateInstance converterType :?> JsonConverter
```

When you have the above converter factory, you can configure the `JsonSerializerOptions` and deserialize with STJ like this:

```fsharp
open AdyenModelSerialization

let jsonDeserializeAdyen<'t> (content: string) =
  let options = JsonSerializerOptions()
  options.Converters.Add(AdyenModelConverterFactory())
  JsonSerializer.Deserialize<'t>(content, adyenJsonSerializerOptions)
```

Please note that this workaround is most likely not very performant. Let me know if you need more information.

**Comment by jillingk** [comment]
Hi @jonekdahl,

Thanks for the explanation, this definitely gives me some inspiration. I think we can make this more performant by interfacing the current converters we have and then implementing this with a custom (optional?) System.Text converter. We have created a ticket for this internally and I'll get started on this very soon. 

Hopefully in the next release we can provide you with some more System.Text support so you will not have to introduce this dependency in your project! 

Best, Jilling
Adyen

**Comment by jonekdahl** [comment]
Sounds good, glad I could provide some inspiration. :+1:

**Comment by wboereboom** [comment]
Unfortunately we do not have the time and resources at this time to implement this feature.

Kind Regards,
Wouter
Adyen
