### ISSUE TITLE
Does this library work with live endpoints?

### ISSUE THREAD

**Issue by LinusCenterstrom** [Adyen/adyen-dotnet-api-library#9]
In the documentation at https://docs.adyen.com/developers/api-reference/live-endpoints
it says that live-endpoints should be prefixed with [random]-[company name]. 

Can i set that somewhere when i use the Live Environment?
(from what i see it uses hardcoded urls without any of those prefixes internally)
Or does it work anyway?

**Comment by AlexandrosMor** [comment]
Hell @LinusCenterstrom,

In the client constructor you can create the Config with the overwritten merchant's endpoint and set the enviroment to live. Here is an example.

`var client = new Client("CompanyPluginDemo", "password",
                Environment.Live, "ApplicationName")
            {
                Config =
                {
                    MerchantAccount = "MerchcantAccount",
                    HmacKey = "12345678912345678900EF84E9CD67C081EDA8984439EAD123456789123456789",
                    SkinCode = "qz7R381z",
                    Endpoint = "https://[random]-[company name]-pal-live.adyenpayments.com/pal/servlet/Payment/[version]/[method]"
                }
            };
        ` 
kind regards,

**Comment by AlexandrosMor** [comment]
Hello @LinusCenterstrom,

Did the above solution worked for you ? Are there more questions for us or we can close the issue?

Thank you in advance,
Alexandros

**Comment by LinusCenterstrom** [comment]
Sorry for the late response, we are still in the process of getting out live env setup, so I haven't been able to test it. But feel free to close the issue and I'll reply to it again if there are any problems.

**Comment by AlexandrosMor** [comment]
Hello @LinusCenterstrom ,

Thank you for your response. Please do not hesitate to contact us if you have any further questions.
Kind regards,
Alexandros

**Comment by KunchalakiranSai** [comment]
Dear Adyen Support Team,

I am writing to request assistance with our payment integration on the Adyen platform. We have encountered an issue with using live endpoints in production and are unable to proceed with our integration.

We have thoroughly tested our integration using the Adyen test environment and have successfully completed all necessary steps. However, when we attempted to switch to the live endpoints for our production environment, we encountered technical difficulties that prevented us from completing transactions.

We have attempted to troubleshoot the issue, but have been unsuccessful in resolving it. We believe that the problem may be related to a configuration issue or an incorrect setup of our production account.

As this issue is affecting our ability to process payments and complete transactions, we kindly request your assistance in resolving this matter as soon as possible. Could you please provide us with guidance on how we can properly set up our production environment to ensure that we can successfully use the live endpoints?

We appreciate your prompt attention to this matter and look forward to hearing back from you soon.
We Have Followed the following SDK : https://mkharibalaji.github.io/react-native-adyen-payment/#/INSTALLATION?id=requirements
