### ISSUE TITLE
Upgraded from 5.7 to 13.2.0 Checkout type not recognised

### ISSUE THREAD

**Issue by dardanshabani** [Adyen/adyen-dotnet-api-library#972]
using Adyen.Service;

 private readonly Checkout checkout;
 checkout = new Checkout(client);

it's not recognised after upgrade, what should I do or change to keep using Checkout class (type).

**Comment by JakkeFiejest** [comment]
I had a similar issue.
a lot of breaking changes were made here:
https://github.com/Adyen/adyen-dotnet-api-library/releases/tag/v11.0.0

**Comment by jillingk** [comment]
Hi @dardanshabani,

Checkout is now split into multiple subservices, as the services in that class have grown quite a lot. If you want to have a nice overview of the (sub)services you can follow our [api-explorer](https://docs.adyen.com/api-explorer/Checkout/71/overview) as this one has the exact same structure as our library methods.

Hi @JakkeFiejest,

Indeed a lot of breaking changes have happened since the last few majors, as we have automated our api libraries since. Please let me know if you need our help upgrading to any of these new versions!

Best, Jilling

**Comment by dardanshabani** [comment]
@jillingk thanks.
